# This is a config for E2B sandbox template.
# You can use template ID (ugemv45o8eo9jy76xsis) or template name (prompt-deck-pynext) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("prompt-deck-pynext") # Sync sandbox
# sandbox = await AsyncSandbox.create("prompt-deck-pynext") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('prompt-deck-pynext')

team_id = "fb3e27e1-0c35-4a36-afc9-ba535a6cb7ee"
start_cmd = "/start_server.sh"
dockerfile = "e2b.Dockerfile"
template_name = "prompt-deck-pynext"
template_id = "ugemv45o8eo9jy76xsis"
